### ISSUE TITLE
Kafka cluster

### ISSUE THREAD

**Issue by santhoshTpixler** [authorjapps/zerocode-docker-factory#3]
Create a Kafka cluster with 3 brokers and 3 zookeepers

**Comment by santhoshTpixler** [comment]
authorjapps/zerocode#151

**Comment by authorjapps** [comment]
PR merged.
See this [Wiki](https://github.com/authorjapps/zerocode-docker-factory/wiki/Docker-container-for-a-single-node-Kafka-broker) page for step by guidance.

**Comment by authorjapps** [comment]
Good work 👍 . PR has been merged now. 

I will take care of the new issue for WIki i.e. https://github.com/authorjapps/zerocode-docker-factory/issues/5
